// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID          int64        `json:"id"`
	UserID      int32        `json:"user_id"`
	CreateAt    sql.NullTime `json:"create_at"`
	UpdateAt    time.Time    `json:"update_at"`
	FinishedAt  time.Time    `json:"finished_at"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	IsDone      sql.NullBool `json:"is_done"`
}

type User struct {
	ID             int64        `json:"id"`
	CreateAt       sql.NullTime `json:"create_at"`
	Username       string       `json:"username"`
	HashedPassword string       `json:"hashed_password"`
	Email          string       `json:"email"`
}
