// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CheckUserExists(ctx context.Context, email string) (bool, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	GetTodoByID(ctx context.Context, id int64) (Todo, error)
	GetTodosByID(ctx context.Context, arg GetTodosByIDParams) ([]Todo, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
