name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 

    services:
      postgres:
        image: postgres:12 
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: tddb 
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps: 

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
        id: go

      - name: Check out the code into the Go module directory
        uses: actions/checkout@v4
            
      - name: Install golang-migration
        run: |
            curl -L -o migrate.deb https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.deb
            sudo dpkg -i migrate.deb
            rm migrate.deb
            which migrate

      - name: Run migration
        run: |
            migrate -path db/migration/ -database "postgresql://root:secret@localhost:5432/tddb?sslmode=disable" -verbose up
      
      - name: Test
        run: go test ./db/sqlc
