name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 

    services:
      postgres:
        image: postgres:12 
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: tddb 
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps: 

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out the code into the Go module directory
        uses: actions/checkout@v2

      - name: Run migration
        uses: migrate -path db/migration/ -database  "postgresql://root:secret@localhost:5432/tddb?sslmode=disable" -verbose up

      - name: Test
        run: go test ./db/sqlc
