name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    name: Build
    runs-on: ubunut-last
  steps:

  - name: Set up Go 1.x
    uses: actions/setup-go@v2
    with:
      go-version: ^1.15
    id: go

  - name: Check out the code into the Go module directory
    uses: actions/checkout@v2

  - name: Test
    run: go test ./db/sqlc

  
